version: '3'
services:
  app:
    container_name: app
    build: .
    ports: 
      - 4321:4000
    depends_on:
      - db
    volumes:
      - .:/workout
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: